# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e964a0102f696a751b191a1433dc303ece1ffc5451afa29b8921fbcac1edc33d795a03e7af6a1c461d830f9c85bf7ecca8b12ba5dd21c448d2c08a3ad136968c

test:
  secret_key_base: 43ad2b7e1c325bbacd2d36f390adcde6c7d296183a812084cbe868139871661fe0fc07154ebaacc7a34b464b85af4f891f918fb4544f2f35969ee825b1b1d04d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
